title: 老吴博客
subtitle: "一个初三人的博客"
description: "这是一个与IT,学生经历有关的一个初三逗比的博客"
author: wuhang2003
language: zh-Hans
timezone: PRC

url: https://hexo.io
root: /
permalink: :year/:month/:day/:title/
archive_dir: archives
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
per_page: 0

index_generator:
  per_page: 5

archive_generator:
  per_page: 20
  yearly: true
  monthly: true

tag_generator:
  per_page: 10

theme: next
deploy:
  type: git
  repo: git@github.com:hexojs/hexojs.github.io.git

highlight:
  enable: true
  line_number: false

disqus_shortname: hexojs
google_analytics: UA-48498357-3
google_adsense: ca-pub-9461880259118621
fb_admins: 100000247608790
algolia:
  applicationID: 'A1T2092KTO'
  apiKey: '428fa2627dd57f046729b301b991fa15'
  adminApiKey: '25feee5e501adb81aeca6e18bccfd7e3'
  indexName: 'wuhang2003'
  chunkSize: 5000
twitter: hexojs
weibo: hexojs
github: hexojs/hexo
